checkpoint: null
device: cuda
prompts: [roof]
gpus_to_use: all
iou_threshold: 0.30
score_threshold_detection: 0.35
new_det_thresh: 0.40
use_decoupled_selection: false
consensus: intersection
save_intermediates: false
