checkpoint: null
device: cuda
prompts: [roof]
gpus_to_use: [0]
iou_threshold: 0.10
score_threshold_detection: 0.10
new_det_thresh: 0.15
use_decoupled_selection: false
use_instance_level_cd: false
instance_iou_threshold: 0.30
t12_min_instance_area: 0
cd_min_instance_area: 0
consensus: intersection
save_intermediates: false
