checkpoint: null
device: cuda
prompts: ["water,river,pond,sea"]
iou_threshold: 0.50
score_threshold_detection: 0.10
new_det_thresh: 0.20
use_decoupled_selection: false
consensus: intersection
save_intermediates: false
