checkpoint: null
device: cuda
prompts: ["low vegetation", grass]
iou_threshold: 0.10
score_threshold_detection: 0.20
new_det_thresh: 0.30
use_decoupled_selection: false
consensus: intersection
save_intermediates: false
