checkpoint: null
device: cuda
prompts: [building]
gpus_to_use: all
iou_threshold: 0.10
score_threshold_detection: 0.30
new_det_thresh: 0.40
use_decoupled_selection: false
consensus: intersection
save_intermediates: false
